spring:
  datasource:
    url: jdbc:mysql://localhost:3307/fasttasty?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update        # crea/actualiza tablas automáticamente
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: false  # Desactivado en producción
  sql:
    init:
      mode: never             # <- NO ejecutar data.sql en prod

vaadin:
  launch-browser: true
